version: "3.5"
services:
  ms2go:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./data:/data
    container_name: ms2go
    command: bash

#  jupyter:
#    image: 'jupyter/datascience-notebook:latest'
#    ports:
#      - 8888:8888
#    volumes:
#      - /tmp/R_and_Jupyter_scripts:/home/jovyan/R_and_Jupyter_scripts
#    working_dir: /home/jovyan/R_and_Jupyter_scripts
#    container_name: jupyter