work = "work.txt"
R_HOME = r"C:\Program Files\R\R-3.6.3"
Reformat_MSstats = "reformatMS_windows_amd64.exe"
split = False
msstats_cutoff = 0.00001
gostats_cutoff = 0.01
gostats_check = True
docker = False
msstats_parallel = 4
